Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2024-07, with the labels that each got.

#3 [chore] #2 - .gradle, .idea 디렉토리 삭제
  .gitignore
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/dependencies-accessors/gc.properties
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileChanges/last-build.bin
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: 동훈🐻

#5 [refactor] #4 - 도메인형 디렉터리 구조 변경 및 local, dev, prod 운영 환경 분리
  src/main/java/com/beat/common/dto/ErrorResponse.java
  src/main/java/com/beat/common/dto/SuccessResponse.java
  src/main/java/com/beat/exception/BadRequestException.java
  src/main/java/com/beat/exception/ForbiddenException.java
  src/main/java/com/beat/exception/NotFoundException.java
  src/main/java/com/beat/exception/UnauthorizedException.java
  src/main/java/com/beat/exception/beatException.java
  src/main/java/com/beat/exception/message/ErrorMessage.java
  src/main/java/com/beat/exception/message/SuccessMessage.java
  src/main/java/com/beat/global/common/config/JpaAuditingConfig.java
  src/main/java/com/beat/global/common/dto/ErrorResponse.java
  src/main/java/com/beat/global/common/dto/SuccessResponse.java
  src/main/java/com/beat/global/common/exception/BadRequestException.java
  src/main/java/com/beat/global/common/exception/BeatException.java
  src/main/java/com/beat/global/common/exception/ForbiddenException.java
  src/main/java/com/beat/global/common/exception/NotFoundException.java
  src/main/java/com/beat/global/common/exception/UnauthorizedException.java
  src/main/java/com/beat/global/common/exception/base/BaseErrorCode.java
  src/main/java/com/beat/global/common/exception/base/BaseSuccessCode.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 동훈🐻

#7 [feat] #6 - dev, prod Dockerfile 분리 및 github Action CI workflow 구현
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  .gitignore
  Dockerfile
  Dockerfile-dev
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
Labels: feat, 동훈🐻, deploy💻

#12 [docs] #11 - 서비스 소개 README v1.0.1 작성 완료
  README.md
Labels: docs, 동훈🐻

#15 [feat] #13 - 유저, 예매, 공연, 회차 엔티티 생성
  src/main/java/com/beat/domain/BaseTimeEntity.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/performance/domain/BankName.java
  src/main/java/com/beat/domain/performance/domain/Genre.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/schedule/domain/ScheduleNumber.java
  src/main/java/com/beat/domain/user/domain/Users.java
Labels: feat, 동훈🐻

#19 [feat] - #18 젠킨스 파일 생성
  Jenkinsfile
Labels: 동훈🐻, deploy💻

#21 [refactor] - #20 push 시 develop 브랜치에 Jenkinsfile에 Webhook이 날아가는지 확인
  Jenkinsfile
Labels: refactor, 동훈🐻, deploy💻

#23 [feat] #22 - CD Jenkins multibranch pipeline 스크립트 작성 완료
  Jenkinsfile
Labels: feat, 동훈🐻, deploy💻

#25 [feat] #24 - slack 연동 스크립트 작성
  Jenkinsfile
Labels: feat, deploy💻

#26 [deploy] merge to main
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  Jenkinsfile
  README.md
  src/main/java/com/beat/domain/BaseTimeEntity.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/performance/domain/BankName.java
  src/main/java/com/beat/domain/performance/domain/Genre.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/schedule/domain/ScheduleNumber.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/domain/user/domain/Users.java
Labels: 동훈🐻, deploy💻

#29 [feat] #28 - 비회원 예매 조회 POST API 구현
  build.gradle
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/application/BookingService.java
  src/main/java/com/beat/domain/booking/application/dto/BookingRetrieveRequest.java
  src/main/java/com/beat/domain/booking/application/dto/BookingRetrieveResponse.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/booking/exception/BookingErrorCode.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/global/common/dto/ErrorResponse.java
  src/main/java/com/beat/global/common/dto/SuccessResponse.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat, 동훈🐻

#31 [feat] #30 - SwaggerConfig 및 WebConfig 구현
  build.gradle
  src/main/java/com/beat/global/common/config/WebConfig.java
  src/main/java/com/beat/global/swagger/SwaggerConfig.java
Labels: feat, 동훈🐻

#33 [feat] #32 - 티켓 예매 가능 여부 GET API 구현
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/schedule/api/ScheduleController.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
  src/main/java/com/beat/domain/schedule/application/dto/TicketAvailabilityRequest.java
  src/main/java/com/beat/domain/schedule/application/dto/TicketAvailabilityResponse.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleErrorCode.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleSuccessCode.java
  src/main/java/com/beat/global/common/exception/ConflictException.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
Labels: feat, 동훈🐻

#36 [feat] #17 - 카카오 소셜 로그인 API 구현
  build.gradle
  src/main/java/com/beat/BeatApplication.java
  src/main/java/com/beat/domain/member/api/MemberController.java
  src/main/java/com/beat/domain/member/application/MemberService.java
  src/main/java/com/beat/domain/member/dao/MemberRepository.java
  src/main/java/com/beat/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/member/domain/SocialType.java
  src/main/java/com/beat/domain/member/dto/AccessTokenGetSuccess.java
  src/main/java/com/beat/domain/member/dto/LoginSuccessResponse.java
  src/main/java/com/beat/domain/member/exception/MemberErrorCode.java
  src/main/java/com/beat/domain/member/exception/MemberSuccessCode.java
  src/main/java/com/beat/domain/user/application/UserService.java
  src/main/java/com/beat/domain/user/application/dto/UserResponse.java
  src/main/java/com/beat/domain/user/dao/UserRepository.java
  src/main/java/com/beat/domain/user/domain/Users.java
  src/main/java/com/beat/global/auth/client/dto/MemberInfoResponse.java
  src/main/java/com/beat/global/auth/client/dto/MemberLoginRequest.java
  src/main/java/com/beat/global/auth/client/kakao/KakaoApiClient.java
  src/main/java/com/beat/global/auth/client/kakao/KakaoAuthApiClient.java
  src/main/java/com/beat/global/auth/client/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/com/beat/global/auth/client/kakao/response/KakaoAccount.java
  src/main/java/com/beat/global/auth/client/kakao/response/KakaoUserProfile.java
  src/main/java/com/beat/global/auth/client/kakao/response/KakaoUserResponse.java
  src/main/java/com/beat/global/auth/client/service/KakaoSocialService.java
  src/main/java/com/beat/global/auth/client/service/SocialService.java
  src/main/java/com/beat/global/auth/jwt/application/TokenService.java
  src/main/java/com/beat/global/auth/jwt/dao/TokenRepository.java
  src/main/java/com/beat/global/auth/jwt/exception/TokenErrorCode.java
  src/main/java/com/beat/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/beat/global/auth/jwt/provider/JwtValidationType.java
  src/main/java/com/beat/global/auth/redis/LettuceLockRepository.java
  src/main/java/com/beat/global/auth/redis/Token.java
  src/main/java/com/beat/global/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/beat/global/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/beat/global/auth/security/MemberAuthentication.java
  src/main/java/com/beat/global/common/config/RedisConfig.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat, 혜린🍀, challenge🏆

#35 [feat] #34 - 비회원 예매 POST API 구현
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/application/BookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRequest.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingResponse.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/performance/dao/PerformanceRepository.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/domain/user/domain/Users.java
  src/main/java/com/beat/domain/user/repository/UserRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: feat, 동훈🐻, challenge🏆

#39 [Refactor] #37 - 카카오 로그인 API response 수정
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/dto/TicketRetrieveResponse.java
  src/main/java/com/beat/domain/booking/dao/TicketRepository.java
  src/main/java/com/beat/domain/member/api/MemberController.java
  src/main/java/com/beat/domain/member/application/MemberService.java
  src/main/java/com/beat/domain/user/repository/UsersRepository.java
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: refactor, 혜린🍀

#41 [feat] #40 - 소개 관련 공연 정보 조회 GET API 구현
  src/main/java/com/beat/domain/cast/dao/CastRepository.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailCast.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailSchedule.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailStaff.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/staff/dao/StaffRepository.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: feat, 혜린🍀

#43 [feat] #42 - 예매 관련 공연 정보 GET API 구현
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/BookingPerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/BookingPerformanceDetailSchedule.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: feat, 혜린🍀

#45 [feat] #38 - 회원 예매 POST API 구현
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingService.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingRequest.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingResponse.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/member/api/MemberController.java
  src/main/java/com/beat/domain/member/exception/MemberErrorCode.java
  src/main/java/com/beat/domain/user/exception/UserErrorCode.java
  src/main/java/com/beat/global/auth/annotation/CurrentMember.java
  src/main/java/com/beat/global/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/beat/global/common/config/WebConfig.java
  src/main/resources/application-dev.yml
Labels: feat, 동훈🐻, challenge🏆

#47 [feat] #44 - 홈페이지 공연 및 홍보 조회 GET API 구현
  src/main/java/com/beat/domain/performance/api/HomeController.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/HomePerformanceDetail.java
  src/main/java/com/beat/domain/performance/application/dto/HomePromotionDetail.java
  src/main/java/com/beat/domain/performance/application/dto/HomeRequest.java
  src/main/java/com/beat/domain/performance/application/dto/HomeResponse.java
  src/main/java/com/beat/domain/performance/dao/PerformanceRepository.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/promotion/dao/PromotionRepository.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
Labels: feat, 혜린🍀, challenge🏆

#48 [feat] #46 - 회원 예매 조회 GET API 구현
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/application/GuestBookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/dto/BookingRetrieveRequest.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRetrieveRequest.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRetrieveResponse.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingRetrieveResponse.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: feat, 동훈🐻

#51 [feat] #49 - 예매자 관리 API 구현
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/booking/application/dto/TicketDeleteRequest.java
  src/main/java/com/beat/domain/booking/application/dto/TicketDetail.java
  src/main/java/com/beat/domain/booking/application/dto/TicketRetrieveResponse.java
  src/main/java/com/beat/domain/booking/application/dto/TicketUpdateDetail.java
  src/main/java/com/beat/domain/booking/application/dto/TicketUpdateRequest.java
  src/main/java/com/beat/domain/booking/dao/TicketRepository.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/booking/exception/BookingErrorCode.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/member/api/MemberController.java
  src/main/java/com/beat/domain/performance/api/HomeController.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/global/auth/client/kakao/KakaoApiClient.java
  src/main/java/com/beat/global/auth/client/kakao/KakaoAuthApiClient.java
Labels: feat, 혜린🍀

#55 [feat] #54 - 등록한 공연 목록 조회 GET API 구현
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/MakerPerformanceDetail.java
  src/main/java/com/beat/domain/performance/application/dto/MakerPerformanceResponse.java
  src/main/java/com/beat/domain/performance/dao/PerformanceRepository.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat, 혜린🍀

#59 [fix] #58 - dev-ci.yml, prod-ci.yml 환경변수 추가
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
Labels: fix, 동훈🐻, deploy💻

#62 [refactor] #61 - Performance Entity field 추가
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
Labels: refactor, 혜린🍀

#64 [feat] #63 - healthCheckController 생성
  src/main/java/com/beat/domain/user/api/HealthCheckController.java
  src/main/java/com/beat/domain/user/repository/UsersRepository.java
Labels: 동훈🐻, deploy💻

#66 [deploy] merge to main
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/user/api/HealthCheckController.java
Labels: 동훈🐻, deploy💻

#65 [fix] #57 - entity 연관관계 설정 SecurityConfig 수정
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: fix, 혜린🍀

#69 [develop] merge to main
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: 혜린🍀, deploy💻

#72 [deploy] merge to main
  src/main/java/com/beat/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: 동훈🐻, deploy💻

#74 [fix] #73 - security 수정
  src/main/java/com/beat/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: fix, 혜린🍀

#75 [deploy] merge to main
  src/main/java/com/beat/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: 동훈🐻, deploy💻

#77 [fix] #76 - Base64 인코딩을 하도록 변경
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: fix, 동훈🐻

#79 [fix] #76 - 누락된 코드 추가
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: bug, 동훈🐻

#82 [fix] #81 - JWT_SECRET을 인코딩하고 이를 다시 인코딩해서 encodedKey를 얻도록 변경
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: bug, 동훈🐻

#83 [deploy] merge to main
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: 동훈🐻, deploy💻

#86 [chore] #85 - 레디스 환경변수 설정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 동훈🐻, deploy💻

#89 [chore] #88 - 레디스 환경변수 추가
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
Labels: 동훈🐻, deploy💻

#94 [fix] #93 - 누락된 어노테이션 및 누락된 경로명 추가
  src/main/java/com/beat/domain/user/api/HealthCheckController.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: fix, 동훈🐻

#96 [bug] #84 - actuator/health 의존성 및 설정 추가
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix, 혜린🍀

#97 devlop에서 main으로 merge
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 혜린🍀, deploy💻

#99 [#98] chore: yml 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix, 혜린🍀

#102 [bug] #101 - yml, s3 수정
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  build.gradle
  src/main/java/com/beat/global/external/s3/S3Config.java
  src/main/java/com/beat/global/external/s3/dao/FileRepository.java
  src/main/java/com/beat/global/external/s3/domain/File.java
  src/main/java/com/beat/global/external/s3/service/FileService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix, 혜린🍀

#108 [feat] #50 - 공연 생성 POST API 생성
  src/main/java/com/beat/domain/performance/api/HomeController.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceCreateService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/create/CastRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/CastResponse.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceResponse.java
  src/main/java/com/beat/domain/performance/application/dto/create/ScheduleRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/ScheduleResponse.java
  src/main/java/com/beat/domain/performance/application/dto/create/StaffRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/StaffResponse.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomePerformanceDetail.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomePromotionDetail.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomeRequest.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomeResponse.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
Labels: feat, 동훈🐻

#114 [feat] #111 - 웹발신 구현
  build.gradle
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/booking/application/CoolSmsService.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat, 혜린🍀

#112 [feat] #110 - 공연 수정 PUT API 구현
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/cast/exception/CastErrorCode.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceUpdateService.java
  src/main/java/com/beat/domain/performance/application/dto/update/CastUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/CastUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/ScheduleUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/ScheduleUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/StaffUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/StaffUpdateResponse.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/domain/staff/exception/StaffErrorCode.java
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: feat, 동훈🐻

#116 [feat] #113 - 공연 삭제 DELETE API 구현
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
Labels: feat, 동훈🐻

#118 [develop] merge to main
  README.md
  build.gradle
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/booking/application/CoolSmsService.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/cast/exception/CastErrorCode.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceUpdateService.java
  src/main/java/com/beat/domain/performance/application/dto/update/CastUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/CastUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/ScheduleUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/ScheduleUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/StaffUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/StaffUpdateResponse.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/domain/staff/exception/StaffErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: deploy💻

#120 [refactor] #119 - response에 필요 필드 추가
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/BookingPerformanceDetailResponse.java
Labels: refactor, 혜린🍀

#121 [feat] #117 - 공연 수정 페이지 정보 조회 GET API 구현
  src/main/java/com/beat/domain/cast/dao/CastRepository.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceCreateService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceEditResponse.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/staff/dao/StaffRepository.java
Labels: feat, 동훈🐻

#124 fix #123 - PerformanceController 중복 코드 제거
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
Labels: fix, 동훈🐻

#125 [deploy] merge to main
  src/main/java/com/beat/domain/cast/dao/CastRepository.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceCreateService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/BookingPerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceEditResponse.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/staff/dao/StaffRepository.java
Labels: 동훈🐻, deploy💻

#129 [#128] fix: 누락된 환경 변수 주입 및 수정
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  src/main/resources/application-dev.yml
Labels: fix, 혜린🍀

#131 [feat] #127 - presigned-url로 포스터 이미지, 등장인물 이미지 리스트, 스태프 이미지 리스트를 반환하도록 구현
  src/main/java/com/beat/global/common/config/SecurityConfig.java
  src/main/java/com/beat/global/external/s3/controller/FileController.java
  src/main/java/com/beat/global/external/s3/service/FileService.java
Labels: feat, 동훈🐻

#134 [refactor] #133 - presigned URL의 만료 시간 늘리기
  src/main/java/com/beat/global/external/s3/dao/FileRepository.java
  src/main/java/com/beat/global/external/s3/domain/File.java
  src/main/java/com/beat/global/external/s3/service/FileService.java
Labels: feat, 동훈🐻

#136 [refactor] #135 - SwaggerConfig 리팩토링
  src/main/java/com/beat/global/swagger/SwaggerConfig.java
Labels: refactor, 동훈🐻

#139 [fix] #138 - bankname enum 추가
  src/main/java/com/beat/domain/performance/domain/BankName.java
Labels: fix, 혜린🍀

#140 [refactor] #126 - 프론트 요청 필드 반영
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/application/GuestBookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingService.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRequest.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingResponse.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRetrieveRequest.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRetrieveResponse.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingRequest.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingResponse.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingRetrieveResponse.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: feat, 동훈🐻

#143 [refactor] #142- castImages, staffImages의 파라미터 value를 주지않아도 posterImages에 대한 presigned-url만 발급할 수 있도록 변경
  src/main/java/com/beat/global/external/s3/controller/FileController.java
Labels: refactor, 동훈🐻

#145 [deploy] merge to main
  src/main/java/com/beat/global/external/s3/controller/FileController.java
Labels: 동훈🐻, deploy💻

#148 [refactor] #147 - 회원, 비회원 예매 조회 시 예금주 필드를 주도록 추가
  src/main/java/com/beat/domain/booking/application/GuestBookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingRetrieveService.java
  src/main/java/com/beat/domain/booking/application/dto/GuestBookingRetrieveResponse.java
  src/main/java/com/beat/domain/booking/application/dto/MemberBookingRetrieveResponse.java
Labels: refactor, 동훈🐻

#155 [deploy] #154 - 배포 전 PROD RDS의 테이블 ddl-auto create로 초기화
  src/main/resources/application-prod.yml
Labels: 동훈🐻, deploy💻

#158 [release] v1.0.0 릴리즈
  src/main/resources/application-prod.yml
Labels: 동훈🐻, release⚡️

#160 [docs] #159 - 서비스 소개 README 작성
  README.md
Labels: docs, 동훈🐻
