Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2024-10, with the labels that each got.

#222 [refactor] #221 - 메인페이지에서 캐러셀 응답 시 캐러셀 번호로 정렬해서 주도록 변경 및 메인 페이지 조회 코드 최적화
  src/main/java/com/beat/admin/adapter/in/api/AdminApi.java
  src/main/java/com/beat/admin/adapter/in/api/AdminController.java
  src/main/java/com/beat/admin/application/AdminService.java
  src/main/java/com/beat/admin/application/dto/request/CarouselHandleRequest.java
  src/main/java/com/beat/admin/application/dto/request/PromotionHandleRequest.java
  src/main/java/com/beat/admin/application/dto/response/CarouselHandleAllResponse.java
  src/main/java/com/beat/admin/facade/AdminFacade.java
  src/main/java/com/beat/admin/port/in/AdminUseCase.java
  src/main/java/com/beat/domain/performance/api/HomeApi.java
  src/main/java/com/beat/domain/performance/api/HomeController.java
  src/main/java/com/beat/domain/performance/application/HomeService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomeFindAllResponse.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomeFindRequest.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomePerformanceDetail.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomePromotionDetail.java
  src/main/java/com/beat/domain/performance/application/dto/home/HomeResponse.java
  src/main/java/com/beat/domain/promotion/application/PromotionService.java
  src/main/java/com/beat/domain/promotion/port/in/PromotionUseCase.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
Labels: refactor, 동훈🐻

#224 [HOTFIX] #223 -캐러셀 삭제 시 promotionId로 판단하도록 수정
  src/main/java/com/beat/admin/application/AdminService.java
  src/main/java/com/beat/admin/facade/AdminFacade.java
  src/main/java/com/beat/admin/port/in/AdminUseCase.java
  src/main/java/com/beat/domain/promotion/application/PromotionService.java
  src/main/java/com/beat/domain/promotion/dao/PromotionRepository.java
  src/main/java/com/beat/domain/promotion/port/in/PromotionUseCase.java
Labels: 동훈🐻, admin, HOTFIX🚑

#226 HOTFIX #225 - ROLE 접두사 중복 오류 해결
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: 동훈🐻, HOTFIX🚑

#228 [HOTFIX] #227 - 권한 체크를 위한 로그 추가
  .github/workflows/dev-CI.yml
  src/main/java/com/beat/domain/member/application/MemberRegistrationService.java
  src/main/java/com/beat/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: 동훈🐻, HOTFIX🚑

#230 HOTFIX #229 - 회원 등록 후 flush()를 호출하여 DB에 반영
  src/main/java/com/beat/domain/member/application/MemberRegistrationService.java
  src/main/java/com/beat/domain/member/application/SocialLoginService.java
Labels: 동훈🐻, HOTFIX🚑

#232 [HOTFIX] #231 - role 관련 상세로그 추가
  src/main/java/com/beat/domain/member/application/SocialLoginService.java
  src/main/java/com/beat/global/auth/jwt/provider/JwtTokenProvider.java
Labels: 동훈🐻, HOTFIX🚑

#234 [HOTFIX] #233 - memberId로 User객체를 잘못 조회했던 문제 해결
  src/main/java/com/beat/admin/facade/AdminFacade.java
  src/main/java/com/beat/domain/member/application/MemberService.java
  src/main/java/com/beat/domain/member/application/SocialLoginService.java
  src/main/java/com/beat/domain/member/port/in/MemberUseCase.java
  src/main/java/com/beat/domain/user/application/UserService.java
  src/main/java/com/beat/domain/user/port/in/UserUseCase.java
Labels: 동훈🐻, HOTFIX🚑

#236 [fix] #235 - 초 단위에 맞게 TTL 변경
  src/main/java/com/beat/global/auth/redis/Token.java
Labels: fix, 동훈🐻

#238 [chore] #237 - Swagger Versioning 업데이트, 서버 url 명시, 사용하지 않는 파일 삭제
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  HELP.md
  src/main/java/com/beat/global/swagger/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 동훈🐻, chore

#242 [refactor] #241 - Swagger 문서화 작업
  src/main/java/com/beat/domain/booking/api/BookingApi.java
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/api/TicketApi.java
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/member/api/MemberApi.java
  src/main/java/com/beat/domain/member/api/MemberController.java
  src/main/java/com/beat/domain/performance/api/PerformanceApi.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/schedule/api/ScheduleApi.java
  src/main/java/com/beat/domain/schedule/api/ScheduleController.java
Labels: refactor, 혜린🍀
