Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2024-09, with the labels that each got.

#205 [fix] #204 - SuccessReponse 메서드 타입 수정 및 회원 예매 조회 타입 일치 완료
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/global/common/dto/SuccessResponse.java
Labels: fix, 동훈🐻

#207 [fix] #206 - 토큰 만료 메시지 status 401로 변경 완료
  src/main/java/com/beat/global/auth/jwt/exception/TokenErrorCode.java
Labels: fix, 동훈🐻, hurry up 🔥

#210 [feat] #209 - Admin 캐러셀 조회, 수정 API 구현
  src/main/java/com/beat/admin/adapter/in/api/AdminApi.java
  src/main/java/com/beat/admin/adapter/in/api/AdminController.java
  src/main/java/com/beat/admin/application/AdminService.java
  src/main/java/com/beat/admin/application/dto/request/CarouselProcessRequest.java
  src/main/java/com/beat/admin/application/dto/request/PromotionHandleRequest.java
  src/main/java/com/beat/admin/application/dto/response/CarouselFindAllResponse.java
  src/main/java/com/beat/admin/application/dto/response/CarouselProcessAllResponse.java
  src/main/java/com/beat/admin/application/dto/response/UserFindAllResponse.java
  src/main/java/com/beat/admin/exception/AdminSuccessCode.java
  src/main/java/com/beat/admin/facade/AdminFacade.java
  src/main/java/com/beat/admin/port/in/AdminUseCase.java
  src/main/java/com/beat/domain/admin/api/AdminApi.java
  src/main/java/com/beat/domain/admin/api/AdminController.java
  src/main/java/com/beat/domain/admin/application/AdminUserManagementService.java
  src/main/java/com/beat/domain/admin/application/dto/UserFindAllResponse.java
  src/main/java/com/beat/domain/admin/application/dto/UserFindResponse.java
  src/main/java/com/beat/domain/member/application/MemberService.java
  src/main/java/com/beat/domain/member/port/in/MemberUseCase.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/port/in/PerformanceUseCase.java
  src/main/java/com/beat/domain/promotion/application/PromotionSchedulerService.java
  src/main/java/com/beat/domain/promotion/application/PromotionService.java
  src/main/java/com/beat/domain/promotion/dao/PromotionRepository.java
  src/main/java/com/beat/domain/promotion/domain/CarouselNumber.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/promotion/exception/PromotionErrorCode.java
  src/main/java/com/beat/domain/promotion/port/in/PromotionUseCase.java
  src/main/java/com/beat/domain/user/application/UserService.java
  src/main/java/com/beat/domain/user/port/in/UserUseCase.java
  src/main/java/com/beat/global/external/s3/api/FileApi.java
  src/main/java/com/beat/global/external/s3/api/FileController.java
  src/main/java/com/beat/global/external/s3/application/FileService.java
  src/main/java/com/beat/global/external/s3/port/in/FileUseCase.java
Labels: feat, 동훈🐻, admin

#199 [fix] #198 - isBooking update 안되는 이슈 해결
  src/main/java/com/beat/BeatApplication.java
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingService.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/global/common/scheduler/application/JobSchedulerService.java
Labels: fix, 혜린🍀

#216 [fix] #215 - 예매자 존재 여부 확인 로직 변경
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
Labels: fix, 혜린🍀

#214 [fix] #211 - 스케쥴 날짜 및 티켓수 변경 관련 에러 처리
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
Labels: fix, 혜린🍀

#218 [fix] #217 - CORS 허용 도메인 환경변수 처리 완료
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  src/main/java/com/beat/global/common/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix, 동훈🐻

#220 [fix] #219 - 캐러셀 번호가 중복된 항목 중에서 promotionId가 다른 경우에만 삭제하도록 수정
  src/main/java/com/beat/admin/application/AdminService.java
  src/main/java/com/beat/admin/facade/AdminFacade.java
  src/main/java/com/beat/admin/port/in/AdminUseCase.java
  src/main/java/com/beat/domain/promotion/application/PromotionService.java
  src/main/java/com/beat/domain/promotion/dao/PromotionRepository.java
  src/main/java/com/beat/domain/promotion/port/in/PromotionUseCase.java
Labels: fix, 동훈🐻, admin
