Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2024-08, with the labels that each got.

#163 [fix] #162 - 공연 삭제 로직 변경
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
Labels: fix, 동훈🐻

#165 [fix] #164 - 입금여부수정 api 경로 수정 및 dev db 초기화
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/resources/application-dev.yml
Labels: fix

#167 [feat] #166 - 사용하지 않는 도커이미지를 서버에서 삭제하도록 Jenkinsfile에 스크립트 추가
  Jenkinsfile
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat, 동훈🐻, deploy💻

#169 [comment] #168 - 불필요한 주석 제거
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/member/application/MemberService.java
Labels: comment

#171 [fix] #170 - 예매자 삭제 시 판매 티켓 수에 반영하는 로직 구현
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleErrorCode.java
Labels: fix

#174 [release] v1.0.1 릴리즈
  Jenkinsfile
  README.md
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/booking/dao/BookingRepository.java
  src/main/java/com/beat/domain/member/application/MemberService.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleErrorCode.java
Labels: 동훈🐻, release⚡️

#175 [feat] #172 - promotion 필드 추가 및 지난 공연 캐러샐 자동 삭제 구현, response에 dueDate 추가
  src/main/java/com/beat/BeatApplication.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/BookingPerformanceDetailSchedule.java
  src/main/java/com/beat/domain/performance/application/dto/MakerPerformanceDetail.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailSchedule.java
  src/main/java/com/beat/domain/promotion/application/PromotionService.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
Labels: feat, 혜린🍀

#179 [feat] #178 - 로그아웃 logging 추가
  src/main/java/com/beat/global/auth/jwt/application/TokenService.java
Labels: feat, 혜린🍀

#181 [#180] refactor - isBooking 로직 조건 개선
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailSchedule.java
  src/main/java/com/beat/domain/schedule/application/ScheduleService.java
Labels: refactor, 혜린🍀

#184 [refactor] #177 - 공연 수정 API에서 회차, 등장인물, 스태프를 추가, 삭제, 업데이트가 가능하도록 리팩토링 및 예매자가 존재하지 않을 시 가격정보 업데이트가 가능하도록 리팩토링
  build.gradle
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceUpdateService.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastAddRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastAddResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastDeleteRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastDeleteResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleAddRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleAddResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleDeleteRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleDeleteResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffAddRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffAddResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffDeleteRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffDeleteResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffUpdateResponse.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/schedule/dao/ScheduleRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: refactor, 동훈🐻, shake up 🌊

#186 [feat] #183 - 공연 등록 시 공연상세이미지 추가 및 상세페이지, 수정페이지에서의 조회 기능 구현과 웹발신 문자내용 수정
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailImage.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceEditResponse.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceImageRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceImageResponse.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceResponse.java
  src/main/java/com/beat/domain/performance/dao/PerformanceImageRepository.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/domain/PerformanceImage.java
  src/main/java/com/beat/global/external/s3/controller/FileController.java
  src/main/java/com/beat/global/external/s3/service/FileService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat, 혜린🍀

#187 [refactor] #185 - schedule, staff, cast의 add, delete, update DTO를 하나의 DTO로 변경 및 scheduleNumber를 서버측에서 부여하도록 변경
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingService.java
  src/main/java/com/beat/domain/cast/dao/CastRepository.java
  src/main/java/com/beat/domain/cast/exception/CastErrorCode.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/PerformanceUpdateService.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/cast/CastModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/cast/CastModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/schedule/ScheduleModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/schedule/ScheduleModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/staff/StaffModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/staff/StaffModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/PerformanceUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastAddRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastAddResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastDeleteRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastDeleteResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/cast/CastUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleAddRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleAddResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleDeleteRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleDeleteResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/schedule/ScheduleUpdateResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffAddRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffAddResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffDeleteRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffDeleteResponse.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffUpdateRequest.java
  src/main/java/com/beat/domain/performance/application/dto/update/staff/StaffUpdateResponse.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleErrorCode.java
  src/main/java/com/beat/domain/staff/dao/StaffRepository.java
  src/main/java/com/beat/domain/staff/exception/StaffErrorCode.java
Labels: refactor, 동훈🐻, shake up 🌊

#189 [feat] #188 - 공연 상세이미지 수정 구현 및 패키지구조 정리, dto 이름 변경
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/BookingPerformanceDetailSchedule.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailCast.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailImage.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailSchedule.java
  src/main/java/com/beat/domain/performance/application/dto/PerformanceDetailStaff.java
  src/main/java/com/beat/domain/performance/application/dto/bookingPerformanceDetail/BookingPerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/bookingPerformanceDetail/BookingPerformanceDetailScheduleResponse.java
  src/main/java/com/beat/domain/performance/application/dto/makerPerformance/MakerPerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/makerPerformance/MakerPerformanceResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/performanceImage/PerformanceImageModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/performanceImage/PerformanceImageModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/performanceDetail/PerformanceDetailCastResponse.java
  src/main/java/com/beat/domain/performance/application/dto/performanceDetail/PerformanceDetailImageResponse.java
  src/main/java/com/beat/domain/performance/application/dto/performanceDetail/PerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/performanceDetail/PerformanceDetailScheduleResponse.java
  src/main/java/com/beat/domain/performance/application/dto/performanceDetail/PerformanceDetailStaffResponse.java
  src/main/java/com/beat/domain/performance/dao/PerformanceImageRepository.java
  src/main/java/com/beat/domain/performance/domain/PerformanceImage.java
  src/main/java/com/beat/domain/performance/exception/PerformanceImageErrorCode.java
Labels: feat, 혜린🍀, comment, rename

#193 [refactor] #192 - 공연소개 & 유의사항 최대 글자수 500자로 구현
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
Labels: refactor, 동훈🐻

#201 [feat] #200 - 공연회차 등록 10회까지 가능하도록 수정
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/schedule/domain/ScheduleNumber.java
Labels: feat, 혜린🍀

#203 feat #202 - allowedMethods에 PATCH 메서드 추가 및 allowedOriginPatterns에 도메인 명시
  src/main/java/com/beat/global/common/config/WebConfig.java
Labels: feat, 동훈🐻, hurry up 🔥
