Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2024-12, with the labels that each got.

#270 [feat] #265 - Enum Custom Converter 구현 및 기타 작업 완료
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyResponse.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/domain/PerformanceImage.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/domain/user/domain/Users.java
  src/main/java/com/beat/global/common/config/WebConfig.java
  src/main/java/com/beat/global/common/converter/StringToEnumCustomConverterFactory.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: fix, feat, 동훈🐻

#271 [fix] #268 - nested DTO가 Swagger에 잡히지 않는 문제 해결
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: fix, 동훈🐻

#273 [fix] #272 - 스웨거에서 ResponseDTO가 잡히지 않는 문제 해결
  src/main/java/com/beat/admin/adapter/in/api/AdminApi.java
  src/main/java/com/beat/domain/booking/api/BookingApi.java
  src/main/java/com/beat/domain/booking/api/TicketApi.java
  src/main/java/com/beat/domain/member/api/MemberApi.java
  src/main/java/com/beat/domain/performance/api/HomeApi.java
  src/main/java/com/beat/domain/performance/api/PerformanceApi.java
  src/main/java/com/beat/domain/schedule/api/ScheduleApi.java
  src/main/java/com/beat/domain/user/api/HealthCheckApi.java
  src/main/java/com/beat/domain/user/api/HealthCheckController.java
  src/main/java/com/beat/global/external/s3/api/FileApi.java
Labels: fix, 동훈🐻

#277 [refactor] #276 - Swagger의 use-fqn 설정을 false로 변경
  src/main/java/com/beat/domain/booking/application/dto/TicketRefundRequest.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: refactor, 동훈🐻

#280 [feat] #279 - Swagger 그룹별 API 경로 설정 및 기타 세부 설정 추가
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: docs, feat, 동훈🐻

#285 [#284] 쿼리 추적을 위한 logging 추가
  src/main/java/com/beat/domain/booking/application/TicketService.java
Labels: fix, 혜린🍀

#287 [feat] #286 - QueryDSL 세팅 완료
  .gitignore
  build.gradle
  src/main/java/com/beat/global/common/config/QueryDslConfig.java
Labels: feat 🎯, 동훈🐻

#289 [feat] #288 - 릴리즈 태그 작성 자동화 구현 완료
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: feat 🎯, 동훈🐻

#292 [chore] #291 - dev 서버에 redis password 설정 추가
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  src/main/java/com/beat/global/common/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 동훈🐻, chore 🔍

#294 [chore] #293 - prod 서버에 redis password 설정 추가
  .github/workflows/prod-CI.yml
  src/main/resources/application-prod.yml
Labels: 동훈🐻, chore 🔍

#296 [fix] #295 - HttpOnly 쿠키에서 자동으로 refreshToken을 추출해 처리하도록 수정 완료
  src/main/java/com/beat/domain/member/api/MemberApi.java
  src/main/java/com/beat/domain/member/api/MemberController.java
  src/main/java/com/beat/domain/member/application/AuthenticationService.java
  src/main/java/com/beat/domain/member/dto/AccessTokenGenerateResponse.java
  src/main/java/com/beat/domain/member/dto/AccessTokenGetSuccess.java
  src/main/java/com/beat/domain/member/dto/MemberLoginResponse.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
Labels: fix 🛠️, 동훈🐻
