Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2024-11, with the labels that each got.

#244 [fix] #243 - 공연 생성 및 수정 시 performancePeriod, scheduleNumber 부여 로직 추가
  src/main/java/com/beat/domain/booking/exception/BookingErrorCode.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/booking/exception/TicketErrorCode.java
  src/main/java/com/beat/domain/cast/exception/CastErrorCode.java
  src/main/java/com/beat/domain/member/exception/MemberErrorCode.java
  src/main/java/com/beat/domain/member/exception/MemberSuccessCode.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/performance/exception/PerformanceImageErrorCode.java
  src/main/java/com/beat/domain/performance/exception/PerformanceSuccessCode.java
  src/main/java/com/beat/domain/promotion/exception/PromotionErrorCode.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleErrorCode.java
  src/main/java/com/beat/domain/schedule/exception/ScheduleSuccessCode.java
  src/main/java/com/beat/domain/staff/exception/StaffErrorCode.java
  src/main/java/com/beat/domain/user/exception/UserErrorCode.java
Labels: fix, 혜린🍀

#250 [feat] #245 - Blue/Green 무중단 배포 구현 완료
  Jenkinsfile
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: 동훈🐻, deploy💻

#252 [refactor] #251 - Jenkinsfile 스크립트 deploy 실행 방식을 sshPut에서 scp 방식으로 변경
  Jenkinsfile
Labels: refactor, 동훈🐻, deploy💻

#253 [refactor] #251 - Jenkinsfile에 자동으로 호스트 키를 신뢰하도록 옵션 추가
  Jenkinsfile
Labels: refactor, 동훈🐻, deploy💻, hurry up 🔥

#255 [HOTFIX] #254 - Jenkinsfile의 scp 방식을 sshPut 방식으로 재변경
  Jenkinsfile
Labels: 동훈🐻, deploy💻, HOTFIX🚑

#258 [feat] #257 - 지도 API 도입
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceResponse.java
  src/main/java/com/beat/domain/performance/application/dto/create/ScheduleRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyResponse.java
  src/main/java/com/beat/domain/performance/application/dto/performanceDetail/PerformanceDetailResponse.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
Labels: feat, 혜린🍀

#260 [feat] #259 - Booking 엔티티 수정 및 환불/취소 요청 API 구현
  src/main/java/com/beat/domain/booking/api/BookingApi.java
  src/main/java/com/beat/domain/booking/api/BookingController.java
  src/main/java/com/beat/domain/booking/application/BookingCancelService.java
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingService.java
  src/main/java/com/beat/domain/booking/application/dto/BookingCancelRequest.java
  src/main/java/com/beat/domain/booking/application/dto/BookingCancelResponse.java
  src/main/java/com/beat/domain/booking/application/dto/BookingRefundRequest.java
  src/main/java/com/beat/domain/booking/application/dto/BookingRefundResponse.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/booking/domain/BookingStatus.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceRequest.java
  src/main/java/com/beat/global/common/config/SecurityConfig.java
Labels: feat, 혜린🍀

#262 [feat] #261 - Ticket 관련 API 구현
  src/main/java/com/beat/domain/booking/api/TicketApi.java
  src/main/java/com/beat/domain/booking/api/TicketController.java
  src/main/java/com/beat/domain/booking/application/BookingCancelService.java
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/booking/application/dto/TicketCancelRequest.java
  src/main/java/com/beat/domain/booking/application/dto/TicketDeleteRequest.java
  src/main/java/com/beat/domain/booking/application/dto/TicketDetail.java
  src/main/java/com/beat/domain/booking/application/dto/TicketRefundRequest.java
  src/main/java/com/beat/domain/booking/application/dto/TicketRetrieveResponse.java
  src/main/java/com/beat/domain/booking/dao/TicketRepository.java
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/booking/exception/BookingSuccessCode.java
  src/main/java/com/beat/domain/booking/exception/TicketErrorCode.java
  src/main/java/com/beat/domain/booking/exception/TicketSuccessCode.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
Labels: feat, 혜린🍀

#264 [fix] #263 - ticketService validation error 해결
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
Labels: fix, 혜린🍀

#266 [feat] #265 - Enum Custom Converter 구현 및 기타 작업 완료
  src/main/java/com/beat/domain/booking/domain/Booking.java
  src/main/java/com/beat/domain/cast/domain/Cast.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/performance/application/PerformanceManagementService.java
  src/main/java/com/beat/domain/performance/application/PerformanceModifyService.java
  src/main/java/com/beat/domain/performance/application/PerformanceService.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceRequest.java
  src/main/java/com/beat/domain/performance/application/dto/create/PerformanceResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyDetailResponse.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyRequest.java
  src/main/java/com/beat/domain/performance/application/dto/modify/PerformanceModifyResponse.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/domain/PerformanceImage.java
  src/main/java/com/beat/domain/promotion/domain/Promotion.java
  src/main/java/com/beat/domain/schedule/domain/Schedule.java
  src/main/java/com/beat/domain/staff/domain/Staff.java
  src/main/java/com/beat/domain/user/domain/Users.java
  src/main/java/com/beat/global/common/config/WebConfig.java
  src/main/java/com/beat/global/common/converter/StringToEnumCustomConverterFactory.java
  src/main/java/com/beat/global/common/handler/GlobalExceptionHandler.java
  src/test/java/com/beat/domain/booking/GuestBookingServiceConcurrencyTest.java
Labels: fix, feat, 동훈🐻
