Repository TEAM-BEAT/BEAT-SERVER, pull requests merged in 2025-01, with the labels that each got.

#298 [refactor] #297 - ticket 조회 및 검색 쿼리문 queryDSL로 리팩토링 완료
  src/main/java/com/beat/domain/booking/application/TicketService.java
  src/main/java/com/beat/domain/booking/dao/TicketRepository.java
  src/main/java/com/beat/domain/booking/dao/TicketRepositoryCustom.java
  src/main/java/com/beat/domain/booking/dao/TicketRepositoryCustomImpl.java
  src/main/java/com/beat/global/common/config/MysqlCustomDialect.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: refactor 🔁, 혜린🍀

#301 [feat] #290 - Prometheus actuator 설정 완료
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  build.gradle
  src/main/java/com/beat/global/common/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat 🎯, 동훈🐻, monitoring 🖥️

#306 [refactor] #305 - 릴리즈 1.2.0 버전과 싱크 맞추기 완료
  README.md
  src/main/java/com/beat/domain/booking/application/GuestBookingService.java
  src/main/java/com/beat/domain/booking/application/MemberBookingService.java
  src/main/java/com/beat/domain/booking/application/dto/TicketCancelRequest.java
  src/main/java/com/beat/domain/member/domain/Member.java
  src/main/java/com/beat/domain/performance/api/PerformanceController.java
  src/main/java/com/beat/domain/performance/domain/Performance.java
  src/main/java/com/beat/domain/performance/exception/PerformanceErrorCode.java
  src/main/java/com/beat/domain/promotion/application/PromotionSchedulerService.java
  src/main/resources/application-dev.yml
Labels: refactor 🔁, 동훈🐻
